{
  parserClass="mitsuko_plugin.parser.MitsukoParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Mitsuko"
  psiImplClassSuffix="Impl"
  psiPackage="mitsuko_plugin.psi"
  psiImplPackage="mitsuko_plugin.psi.impl"

  elementTypeHolderClass="mitsuko_plugin.psi.MitsukoTypes"
  elementTypeClass="mitsuko_plugin.psi.MitsukoElementType"
  tokenTypeClass="mitsuko_plugin.psi.MitsukoTokenType"
}

mitsukoFile ::= item_?

private item_ ::= WHITE1* (FUNCTION_FILE | PACK_FILE | ITEM_FILE)

FUNCTION_FILE ::= HEADER_FN_FILE (TAG|COMMENT|CRLF|FUNCTION|WHITE1)+

FUNCTION ::= FN_DEFINE FN_BODY

FN_BODY ::= FN_OPEN (CODE | COMMENT | CRLF | WHITE1)* FN_CLOSE

CODE ::= BLOCK | ((FOR | CODE_CUSTOM | COMMAND_START | SHORT_SCORE | FLOW | FN_OPEN | VALUE) ((SCOREBOARD !(W SCORE_OPERATION)) | VALUE | EQUALS | (E_SELECTOR !EQUALS) | SUB_CUSTOM | PIDENT | EXE_SUB | SUB_1 | SUB_2 | SUB_UNKNOWN | WHITE1 | NBT)* CODE?) | FN_CALL

FOR ::= CODE_CUSTOM W PARENS SCOREBOARD COMMA W (PIDENT | VALUE) (COMMA W (PIDENT | VALUE))? PARENS

FLOW ::= FLOW_CONTROL W PARENS (CONDITION W)+ PARENS

BLOCK ::= BLOCK_OPEN (CODE | COMMENT | CRLF | WHITE1)* BLOCK_CLOSE

CONDITION ::= (SUB_1 | SUB_2 | SUB_UNKNOWN | SCOREBOARD | (E_SELECTOR !EQUALS) | SCORE_OPERATION | PIDENT | NBT | VALUE)+

TAG ::= (TAG_DEF TAG_NAME EQUALS TAG_VALUE TAG_DEF) {methods=[getName]}

FN_DEFINE ::= (FN_KEYWORD FN_NAME)

NBT ::= (NBT_BRACES W NBT_INTERNAL*) | (NBT_STRING+)

NBT_INTERNAL ::= (NBT_PROPERTY | (EQUALS W NBT_INTERNAL) | COMMA | NBT_VALUE | NBT_STRING | CODE_CUSTOM | NBT_BRACES | VALUE) W

E_SELECTOR ::= SELECTOR NBT?

SCOREBOARD ::= (E_SELECTOR EQUALS SCORE_NAME) | (SCOREBOARD_TEMP) | VALUE

SHORT_SCORE ::= (SCOREBOARD W SCORE_OPERATION W ((SCOREBOARD !(W SCORE_OPERATION)) | PIDENT | CODE)?) | (SCOREBOARD W CRLF) 

W ::= WHITE1*

PACK_FILE ::= HEADER_PACK_FILE ((W TAG_NAME W EQUALS W TAG_VALUE W) | WHITE1)+

ITEM_FILE ::= HEADER_ITEM_FILE ((ITEM_GROUP W BLOCK_OPEN W (ITEM_CONTENT W)+ BLOCK_CLOSE) | WHITE1 | (ITEM_GROUP W EQUALS W TAG_VALUE))+

ITEM_CONTENT ::= NBT_STRING | (TAG_NAME W EQUALS W TAG_VALUE) | (CODE | COMMENT | CRLF | WHITE1)+